@host = http://127.0.0.1:{{$dotenv PORT}}
@quizId = 1234567
@quizPassword = ultimateQuizPassword

# Create quiz endpoint
POST {{host}}/quiz/create
Content-Type: application/json

{
   "title": "True or False",
   "password": "{{quizPassword}}",
   "questions": [
      {
         "text": "Are you a developer?",
         "answers": ["true", "t"]
      },
      {
         "text": "Do you have a girlfriend?",
         "answers": ["false", "f"]
      }
   ]
}

###

# Get quiz results endpoint
POST {{host}}/quiz/results/{{quizId}}
Content-Type: application/json

{
   "password": "{{quizPassword}}"
}

###

# Pass quiz endpoint
POST {{host}}/quiz/pass/{{quizId}}
Content-Type: application/json

{
   "name": "John Doe",
   "answers": [
      {
         "questionId": "12345",
         "answer": "true"
      },
      {
         "questionId": "22346",
         "answer": "false"
      }
   ]
}

###

# Take quiz endpoint
GET {{host}}/quiz/take/{{quizId}}

###

# Disable quiz endpoint
PATCH {{host}}/quiz/disable/{{quizId}}
Content-Type: application/json

{
   "password": "{{quizPassword}}"
}
